#!/bin/bash
# Only change these 2 paths if you want to compile a kernel on your own
export ARM_EABI=$HOME/Codesourcery/toolchain/bin/arm-eabi-
export BUILD_DIR=$HOME/Dropbox/Public
export SCRIPT_DIR=$HOME/vorkKernel-Scripts
export SOURCE_DIR=$HOME/CMKernelLG/lge-kernel-star

rm $SCRIPT_DIR/CMScripts/Tools/ramdisk-boot
rm $SCRIPT_DIR/CMScripts/Tools/newBoot.img
DIR=$PWD
echo "Do you want to build a release or a test version?"
echo "1 for Release, 2 for Test"
read BUILD
case $BUILD in
	1) export release=release 
	;;
	2) export release=test 
	;;
esac 
clear
. Scripts/kernelcompile.sh
clear
. Scripts/kernelpack.sh
python Scripts/pyndexer/pyndexer.py

