#!/system/bin/sh

exec &> /dev/null

# Make sure android is ready for intents
while [ `pidof com.android.systemui` == "" ]; do
	sleep 10
done

# Start headsetbooster
am start -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000 -n com.kupulau.screennotifier/com.kupulau.headsetbooster.HeadsetBoosterSettings
