#!/system/bin/sh

battery_safe_freqs = "216000 312000 456000 608000 816000 912000 1000000 1100000"
battery_safe_volts = "750 775 800 850 900 975 1025 1100"
cpufreq = "/sys/devices/system/cpu/cpu0/cpufreq"

if [ -f $cpufreq/scaling_step_freqs && -f $cpufreq/scaling_step_volts ]; then
	echo $battery_safe_freqs > $cpufreq/scaling_step_freqs
	echo $battery_safe_volts > $cpufreq/scaling_step_volts
fi